### PR TITLE
fix: convert to ES6, format code

### PR DESCRIPTION
**Pull request by carrotfarmer**
Hi

**Changes**:
- Convert to use `const` and arrow functions in `theme.js` and `comment.js`
- Renamed util function `I` in `comment.js` to `getElemById` for more readability

### CODE REVIEW

**Comment by gouravkhunger** [comment]
Hey, I get this error while testing your changes:

image

At [this line number](https://github.com/carrotfarmer/theme-files/blob/main/assets/js/comment.js#L48).\
Can you check what's causing it? It works fine in the current script though.

**Comment by carrotfarmer** [comment]
@gouravkhunger Sure

**Comment by carrotfarmer** [comment]
@gouravkhunger Could you tell how I can test the changes?

**Comment by Posandu** [comment]
you use `this` that is a keyword in JS. so replace it with `_this`

**Comment by carrotfarmer** [comment]
i changed it back to `I` since the whole point of creating this function was to shorten the code required to call it. I just added a small comment on top to specify what its doing

**Pull request merged**
