### PR TITLE
Animate nav menu icon transition

### PR DESCRIPTION
**Pull request by androlover98**
An enhancement for issue #15 

Sticking to div based animation because animating svgs wasn't giving smooth results without introducing dependencies.

https://user-images.githubusercontent.com/24232447/193819784-a67d50ab-8832-492b-b0ed-2ae10263e8c6.mov

### CODE REVIEW

**Comment by gouravkhunger** [comment]
Hey @androlover98 I already have logic for such animation implemented for my [portfolio website](https://gouravkhunger.me). I didn't implement it here because I wished to have an animation similar to the example I shared in that issue.

Would it be possible for you, to like see how it is done in [beyondwords.io](https://beyondwords.io) to implement similarly here as well?

Else we will go with some other alternative. Thanks!

**Comment by gouravkhunger** [comment]
yeah I saw that haha

**Comment by androlover98** [comment]
Updated 

https://user-images.githubusercontent.com/24232447/194156640-179c6873-0258-49ec-abc7-1b1051d24edc.mo

**Review by gouravkhunger — APPROVED** [review]
Thanks! This looks good now.

**Pull request merged**
