### PR TITLE
feat: keyboard shortcut indicator for search

### PR DESCRIPTION
**Pull request by carrotfarmer**
Fixes #13 

- Adds a `ctrl+k` keyboard shortcut indicator in the search bar on the home page. (Adapts to light and dark mode)
- Format code

PFA Screenshots:
image
image
image
image

### CODE REVIEW

**Comment by Posandu** [comment]
Dead project

**Comment by carrotfarmer** [comment]
@gouravkhunger is this ok?

**Comment by gouravkhunger** [comment]
@carrotfarmer needs some improvement on top of this, will do it myself today 👍🏻

**Comment by carrotfarmer** [comment]
ok sure

**Comment by gouravkhunger** [comment]
image

image

image

**Review by gouravkhunger — APPROVED** [review]
Thanks!

**Pull request merged**
